name: Build

on:
  push:
    branches:
      - main

jobs:
  build:
    name: build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout triggering commit
        uses: actions/checkout@v4

      - name: Setup QEMU for multi-arch
        uses: docker/setup-qemu-action@v3

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build
        run: ./build.sh build
        env:
            REPO_OWNER: ${{ github.repository_owner }}
